// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/storage/reportstorage.proto

package timereport_storage

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
	api "proto/api"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ReportEntity struct {
	Timestamp            int64    `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Tag                  string   `protobuf:"bytes,3,opt,name=tag,proto3" json:"tag,omitempty"`
	Username             string   `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReportEntity) Reset()         { *m = ReportEntity{} }
func (m *ReportEntity) String() string { return proto.CompactTextString(m) }
func (*ReportEntity) ProtoMessage()    {}
func (*ReportEntity) Descriptor() ([]byte, []int) {
	return fileDescriptor_ebe35b4fcc63e032, []int{0}
}

func (m *ReportEntity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReportEntity.Unmarshal(m, b)
}
func (m *ReportEntity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReportEntity.Marshal(b, m, deterministic)
}
func (m *ReportEntity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReportEntity.Merge(m, src)
}
func (m *ReportEntity) XXX_Size() int {
	return xxx_messageInfo_ReportEntity.Size(m)
}
func (m *ReportEntity) XXX_DiscardUnknown() {
	xxx_messageInfo_ReportEntity.DiscardUnknown(m)
}

var xxx_messageInfo_ReportEntity proto.InternalMessageInfo

func (m *ReportEntity) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *ReportEntity) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ReportEntity) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *ReportEntity) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func init() {
	proto.RegisterType((*ReportEntity)(nil), "timereport.storage.ReportEntity")
}

func init() { proto.RegisterFile("proto/storage/reportstorage.proto", fileDescriptor_ebe35b4fcc63e032) }

var fileDescriptor_ebe35b4fcc63e032 = []byte{
	// 224 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x90, 0xc1, 0x4a, 0x03, 0x31,
	0x10, 0x86, 0x89, 0x2b, 0x6a, 0x87, 0x1e, 0xca, 0x9c, 0xe2, 0xd2, 0xc3, 0xea, 0xa9, 0xa7, 0x54,
	0xf4, 0x19, 0xec, 0xb9, 0xac, 0x4f, 0x30, 0xca, 0xb0, 0x06, 0x4c, 0x13, 0x92, 0x51, 0xd8, 0x17,
	0xf3, 0xf9, 0x24, 0xc9, 0xaa, 0x0b, 0x3d, 0xec, 0x25, 0xe4, 0xff, 0xfe, 0xf9, 0x27, 0x99, 0x81,
	0xbb, 0x10, 0xbd, 0xf8, 0x7d, 0x12, 0x1f, 0x69, 0xe0, 0x7d, 0xe4, 0xe0, 0xa3, 0x4c, 0xca, 0x14,
	0x0f, 0x51, 0xac, 0xe3, 0x6a, 0x98, 0xc9, 0x69, 0x6f, 0x6b, 0x8c, 0x82, 0x9d, 0x22, 0x14, 0x6c,
	0x2d, 0xbf, 0x17, 0x58, 0xf7, 0x05, 0x3d, 0x9f, 0xc4, 0xca, 0x88, 0x5b, 0x58, 0xe5, 0x06, 0x49,
	0xc8, 0x05, 0xad, 0x3a, 0xb5, 0x6b, 0xfa, 0x7f, 0x80, 0x1a, 0xae, 0x1d, 0xa7, 0x44, 0x03, 0xeb,
	0x8b, 0x4e, 0xed, 0x56, 0xfd, 0xaf, 0xc4, 0x0d, 0x34, 0x42, 0x83, 0x6e, 0x0a, 0xcd, 0x57, 0x6c,
	0xe1, 0xe6, 0x33, 0x71, 0x3c, 0x91, 0x63, 0x7d, 0x59, 0xf0, 0x9f, 0x7e, 0xfc, 0x56, 0xb0, 0xa9,
	0xcf, 0xe6, 0x33, 0x59, 0xf1, 0x71, 0xc4, 0x23, 0xc0, 0x0b, 0x7d, 0x71, 0xe5, 0xd8, 0x99, 0xf3,
	0x41, 0xcc, 0xfc, 0xab, 0xed, 0x62, 0x05, 0x1e, 0x61, 0x7d, 0x60, 0x79, 0x7b, 0xaf, 0x30, 0xe1,
	0x76, 0x9e, 0xc8, 0x3b, 0xa8, 0xc6, 0xc1, 0x7e, 0x08, 0xc7, 0xe5, 0x7e, 0x0f, 0xea, 0xf5, 0xaa,
	0x6c, 0xed, 0xe9, 0x27, 0x00, 0x00, 0xff, 0xff, 0x67, 0x3b, 0x84, 0xc9, 0x89, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ReportRepositoryClient is the client API for ReportRepository service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ReportRepositoryClient interface {
	SaveReport(ctx context.Context, in *ReportEntity, opts ...grpc.CallOption) (*ReportEntity, error)
	FetchReports(ctx context.Context, in *api.ReportFilter, opts ...grpc.CallOption) (ReportRepository_FetchReportsClient, error)
}

type reportRepositoryClient struct {
	cc grpc.ClientConnInterface
}

func NewReportRepositoryClient(cc grpc.ClientConnInterface) ReportRepositoryClient {
	return &reportRepositoryClient{cc}
}

func (c *reportRepositoryClient) SaveReport(ctx context.Context, in *ReportEntity, opts ...grpc.CallOption) (*ReportEntity, error) {
	out := new(ReportEntity)
	err := c.cc.Invoke(ctx, "/timereport.storage.ReportRepository/SaveReport", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reportRepositoryClient) FetchReports(ctx context.Context, in *api.ReportFilter, opts ...grpc.CallOption) (ReportRepository_FetchReportsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ReportRepository_serviceDesc.Streams[0], "/timereport.storage.ReportRepository/FetchReports", opts...)
	if err != nil {
		return nil, err
	}
	x := &reportRepositoryFetchReportsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ReportRepository_FetchReportsClient interface {
	Recv() (*ReportEntity, error)
	grpc.ClientStream
}

type reportRepositoryFetchReportsClient struct {
	grpc.ClientStream
}

func (x *reportRepositoryFetchReportsClient) Recv() (*ReportEntity, error) {
	m := new(ReportEntity)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ReportRepositoryServer is the server API for ReportRepository service.
type ReportRepositoryServer interface {
	SaveReport(context.Context, *ReportEntity) (*ReportEntity, error)
	FetchReports(*api.ReportFilter, ReportRepository_FetchReportsServer) error
}

// UnimplementedReportRepositoryServer can be embedded to have forward compatible implementations.
type UnimplementedReportRepositoryServer struct {
}

func (*UnimplementedReportRepositoryServer) SaveReport(ctx context.Context, req *ReportEntity) (*ReportEntity, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveReport not implemented")
}
func (*UnimplementedReportRepositoryServer) FetchReports(req *api.ReportFilter, srv ReportRepository_FetchReportsServer) error {
	return status.Errorf(codes.Unimplemented, "method FetchReports not implemented")
}

func RegisterReportRepositoryServer(s *grpc.Server, srv ReportRepositoryServer) {
	s.RegisterService(&_ReportRepository_serviceDesc, srv)
}

func _ReportRepository_SaveReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportEntity)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReportRepositoryServer).SaveReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/timereport.storage.ReportRepository/SaveReport",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReportRepositoryServer).SaveReport(ctx, req.(*ReportEntity))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReportRepository_FetchReports_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(api.ReportFilter)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ReportRepositoryServer).FetchReports(m, &reportRepositoryFetchReportsServer{stream})
}

type ReportRepository_FetchReportsServer interface {
	Send(*ReportEntity) error
	grpc.ServerStream
}

type reportRepositoryFetchReportsServer struct {
	grpc.ServerStream
}

func (x *reportRepositoryFetchReportsServer) Send(m *ReportEntity) error {
	return x.ServerStream.SendMsg(m)
}

var _ReportRepository_serviceDesc = grpc.ServiceDesc{
	ServiceName: "timereport.storage.ReportRepository",
	HandlerType: (*ReportRepositoryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SaveReport",
			Handler:    _ReportRepository_SaveReport_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "FetchReports",
			Handler:       _ReportRepository_FetchReports_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/storage/reportstorage.proto",
}
